ARG phpImg=php:apache
FROM $phpImg
ENV APACHE_PORT=19290 SESSION_MODULE=redis SESSION_PATH=tcp://redis DATABASE_URL=mysql://grimauser:grimapass@mysql/grimadb
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
  && apt-get update && apt-get install -y libpq-dev \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && docker-php-ext-install pdo pdo_mysql pdo_pgsql \
  ; true
COPY vhost.conf /etc/apache2/sites-enabled/000-default.conf
COPY ports.conf /etc/apache2/ports.conf
EXPOSE $APACHE_PORT
COPY dist /var/www/html
